In [1]:
import torch
from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
from gluonnlp.data import SentencepieceTokenizer
from kogpt2.utils import get_tokenizer

In [2]:
tok_path = get_tokenizer()
model, vocab = get_pytorch_kogpt2_model()

using cached model
using cached model
using cached model


In [3]:
tok_path

'C:\\Users\\bitcamp/kogpt2/kogpt2_news_wiki_ko_cased_818bfa919d.spiece'

In [4]:
vocab

Vocab(size=50000, unk="<unk>", reserved="['<pad>', '<s>', '</s>']")

In [5]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50000, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): Laye

In [ ]:
model

In [142]:
Tokenizer = SentencepieceTokenizer(tok_path,  num_best=0, alpha=0)
test = '2019년 한해를 보내며,'
toked_test = Tokenizer(test)

In [143]:
toked_test

['▁2019', '년', '▁한', '해를', '▁보내', '며', ',']

In [144]:
vocab

Vocab(size=50000, unk="<unk>", reserved="['<pad>', '<s>', '</s>']")

In [145]:
vocab.eos_token

'</s>'

In [146]:
vocab['안녕']

28911

In [147]:
vocab['김민지']

5

In [148]:
vocab['문재인']

8116

In [149]:
vocab['sk']

11444

In [150]:
vocab[vocab.bos_token]
# vocab[vocab.eos_token]
# vocab[vocab.mask_token]

0

In [151]:
vocab[toked_test]

[13094, 47504, 118, 3175, 2021, 47559, 47453]

In [152]:
input_idex = torch.tensor([vocab[vocab.bos_token]]  + vocab[toked_test]).unsqueeze(0)
input_idex

tensor([[    0, 13094, 47504,   118,  3175,  2021, 47559, 47453]])

In [153]:
pred = model(input_idex)

In [154]:
len(pred)

2

In [155]:
pred[0]

tensor([[[  2.5165,   4.4752, -10.7885,  ...,  -5.0155,  -6.3820,  -5.6697],
         [  2.2034,   7.7850,  -8.9211,  ...,  -3.7880,  -4.1200,  -2.6476],
         [  0.7305,   7.1286, -11.1899,  ...,  -5.4412,  -7.5393,  -5.4415],
         ...,
         [  0.6824,   8.1053, -10.1805,  ...,  -2.3225,   0.6867,  -2.0107],
         [ -0.4727,   7.2838, -11.6744,  ...,  -4.7894,  -6.8361,  -5.7711],
         [ -1.3252,   6.5092, -10.8941,  ...,  -3.9049,  -7.4099,  -5.7560]]],
       grad_fn=<UnsafeViewBackward>)

In [156]:
pred[1]

(tensor([[[[[ 4.6505e-02, -2.2171e-01, -1.9005e+00,  ...,  2.2644e+00,
             -6.1944e-01,  1.0766e-01],
            [-3.8876e-01, -4.4565e-01, -1.0235e+00,  ...,  1.8908e+00,
             -1.3399e+00,  1.0579e+00],
            [ 3.3694e-01,  8.1811e-01, -1.1906e+00,  ...,  2.4225e+00,
             -1.7827e+00,  1.0195e+00],
            ...,
            [ 2.2819e+00,  8.9213e-01, -8.5244e-01,  ...,  3.8796e-01,
             -1.3744e+00,  1.7030e+00],
            [ 1.6118e-01,  1.8049e+00, -5.6426e-01,  ...,  9.7062e-01,
             -6.4213e-01,  4.1554e-01],
            [ 9.6109e-01,  9.6463e-01, -8.2757e-01,  ...,  1.3084e+00,
             -1.8399e+00,  8.7054e-01]],
 
           [[-8.7631e-02, -4.8695e-01, -5.5214e-01,  ..., -1.6524e-01,
             -1.4010e-01,  1.7843e-01],
            [ 1.1605e+00, -2.5704e-01, -4.1558e-01,  ..., -3.4952e-01,
              7.4145e-01,  5.0728e-01],
            [ 1.3370e+00, -6.6201e-01,  7.2899e-01,  ..., -3.2812e-01,
              5.4273e

In [157]:
pred = model(input_idex)[0]
pred

tensor([[[  2.5165,   4.4752, -10.7885,  ...,  -5.0155,  -6.3820,  -5.6697],
         [  2.2034,   7.7850,  -8.9211,  ...,  -3.7880,  -4.1200,  -2.6476],
         [  0.7305,   7.1286, -11.1899,  ...,  -5.4412,  -7.5393,  -5.4415],
         ...,
         [  0.6824,   8.1053, -10.1805,  ...,  -2.3225,   0.6867,  -2.0107],
         [ -0.4727,   7.2838, -11.6744,  ...,  -4.7894,  -6.8361,  -5.7711],
         [ -1.3252,   6.5092, -10.8941,  ...,  -3.9049,  -7.4099,  -5.7560]]],
       grad_fn=<UnsafeViewBackward>)

In [158]:
test

'2019년 한해를 보내며,'

In [159]:
vocab.to_tokens(torch.argmax(pred, axis=-1).squeeze().tolist())
# [:-1]은 더미값이 온다.

['▁이', '년', '▁1', '▁해', '▁마무리', '며', ',', '▁새해']

In [160]:
new_token = vocab.to_tokens(torch.argmax(pred, axis=-1).squeeze().tolist())[-1]

In [161]:
test += new_token.replace('▁', ' ')

In [162]:
test

'2019년 한해를 보내며, 새해'

In [163]:
toked_test = tok(test)
toked_test

['▁2019', '년', '▁한', '해를', '▁보내', '며', ',', '▁새해']

In [164]:
input_idex = torch.tensor([vocab[vocab.bos_token],]  + vocab[toked_test]).unsqueeze(0)

In [165]:
pred = model(input_idex)[0]

In [166]:
vocab.to_tokens(torch.argmax(pred, axis=-1).squeeze().tolist())

['▁이', '년', '▁1', '▁해', '▁마무리', '며', ',', '▁새해', '에는']

In [167]:
new_token = vocab.to_tokens(torch.argmax(pred, axis=-1).squeeze().tolist())[-1]

In [168]:
test += new_token.replace('▁', ' ')

In [169]:
test

'2019년 한해를 보내며, 새해에는'

In [170]:
toked_test = tok(test)

In [171]:
while 1:
    input_idex = torch.tensor([vocab[vocab.bos_token]]  + vocab[toked_test]).unsqueeze(0)
    pred = model(input_idex)[0]
    new_token = vocab.to_tokens(torch.argmax(pred, axis=-1).squeeze().tolist())[-1]
    if new_token == '</s>':
      break
    test += new_token.replace('▁', ' ')
    print(test)
    print('==============================================')
    toked_test = tok(test)
    

2019년 한해를 보내며, 새해에는 더
2019년 한해를 보내며, 새해에는 더 많은
2019년 한해를 보내며, 새해에는 더 많은 사람들이
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이 되었
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이 되었으면
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이 되었으면 좋겠다
2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이 되었으면 좋겠다.


In [172]:
test

'2019년 한해를 보내며, 새해에는 더 많은 사람들이 새해에 이루고자 하는 소망과 희망을 되새겨보는 시간이 되었으면 좋겠다.'